services:
  - type: web
    name: carecompanion-api
    env: python
    region: oregon
    plan: free
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y tesseract-ocr libtesseract-dev
      python -m pip install --upgrade pip
      pip install -e .
      python -m spacy download en_core_web_sm
    startCommand: uvicorn app:app --host=0.0.0.0 --port=10000
    autoDeploy: true
