services:
  - type: web
    name: carecompanion-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH="." gunicorn app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    autoDeploy: true
    runtime: python3.11
    healthCheckPath: /docs
