services:
  - type: web
    name: carecompanion-ocr-api
    env: python
    plan: free
    branch: main
    rootDirectory: OCR
    buildCommand: |  # <-- FIX HERE (MULTI-LINE COMMAND)
      chmod +x ./build.sh
      ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: OCR_API_KEY
        value: mykey01  # <-- REPLACE WITH ACTUAL KEY IN RENDER DASHBOARD
