services:
  - type: web
    name: carecompanion-summarizer
    runtime: python
    repo: https://github.com/Aadityaramrame/carecompanion-deploy
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
